<?php
/**
 * Услуга
 *
 * @var umiTemplaterPHP|ViewPhpExtension|gortisPhpExtension $this
 * @var array                                               $variables
 */

$items = $this->macros('content', 'menu', [null, 1, $variables['pageId']], ['anons']);
?>

<main class="container wrapper">
    <section class="s_service">
        <div class="service">
            <?php
            if ($variables['page']->getValue('top_photo')): ?>
                <img src="<?= $this->macros(
                    'system',
                    'makeThumbnailFull',
                    [$variables['page']->getValue('top_photo')->getFilePath(), 900, 'auto']
                )['src'] ?>" alt="photo">
            <?php
            endif; ?>

            <?php if($variables['page']->getValue('additional_title')):?>
                <div class="innerTitle">
                    <?= $variables['page']->getValue('additional_title') ?>
                </div>
            <?php endif;?>

            <?php if($variables['page']->getValue('quote')):?>
                <div class="service__quote">
                    <div class="service__quote__icon">
                        <img src="<?= $this->getCommonVar('base') ?>images/left-quote.png" alt="icon">
                    </div>
                    <p class="service__quote__content">
                        <?= $variables['page']->getValue('quote') ?>
                    </p>
                </div>
            <?php endif;?>

            <?php if($variables['page']->getValue('content')):?>
                <div class="service__content">
                    <?= $variables['page']->getValue('content') ?>
                </div>
            <?php endif;?>

            <?php if ($items): ?>
                <div class="service__items">
                    <?= $this->render($items, 'news/service/similar') ?>
<!--                    --><?php //if ($variables['page']->getValue('similar_services')): ?>
<!--                    --><?php //endif; ?>
                </div>
            <?php endif; ?>

            <div class="service__content subcontent">
                <?= $variables['page']->getValue('subcontent') ?>
            </div>

        </div>
    </section>

    <?= $this->render($variables, 'news/service/aside') ?>
</main>
