<?php
/**
 * Услуги из поля "ссылка на дерево"
 *
 * @var umiTemplaterPHP|ViewPhpExtension|gortisPhpExtension $this
 * @var array                                               $variables
 */

foreach ($variables['items'] as $service): ?>

    <a href="<?= $service['link'] ?>" class="service__items__item">
        <div class="border">
            <div class="help__items__link">
                <p>
                    <img src="<?= $this->getCommonVar('base') ?>images/down-arrow-light.png" alt="icon">
                </p>
            </div>
            <div class="service__items__item__content">
                <div class="service__items__item__content__title">
                    <?= $service['name']; ?>
                </div>
                <?= $service['extended']['properties'][0]->getValue() ?>
            </div>
        </div>
    </a>
<?php
endforeach;
