<?php
/**
 * Шаблон ленты новостей
 *
 * @var umiTemplaterPHP|ViewPhpExtension|gortisPhpExtension $this
 * @var array                                               $variables
 */

if (
    (int)$variables['pageId'] === 13 ||
    (!empty($variables['parents'] && $variables['parents'][0]->getId() === 13))
): ?>
    <?= $this->render($variables, 'news/services/index') ?>
<?php
else: ?>
<?= $this->render($variables, 'news/news/index') ?>
<?php
endif;
