<?php
/**
 * Страница контакты
 *
 * @var umiTemplaterPHP|ViewPhpExtension|gortisPhpExtension $this
 * @var array                                               $variables
 */

?>

<section class="s_content">
    <div class="wrapper">
        <div class="content">
            <div class="wrapHalf">
                <div class="wrapHalf__item">
                    <?= $variables['page']->getValue('content') ?>
                </div>
                <div class="wrapHalf__item">
                    <h2>Схема проезда:</h2>
                    <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A74caf7ed1c7395a51e249a614e3ae8e9c5d0e4b2075dfff94bb4113bd8c94ce7&amp;width=100%25&amp;height=400&amp;lang=ru_RU&amp;scroll=true"></script>
                </div>
            </div>
        </div>
    </div>
</section>