<?php
/**
 * Чекбокс с правами на обработку данных
 *
 * @var umiTemplaterPHP|ViewPhpExtension|gortisPhpExtension $this
 * @var array                                               $variables
 */

?>
<div class="modal-form__row">
    <label><input type="checkbox" class="notice_cheked" checked name="notice"/>
        Отправляя заявку, я соглашаюсь на обработку персональных данных
    </label>
</div>
