<?php
/**
 * Список услуг
 *
 * @var umiTemplaterPHP|ViewPhpExtension|gortisPhpExtension $this
 * @var array                                               $variables
 */

?>

    <section class="s_servicesBlock">
        <div class="wrapper">
            <div class="servicesBlock">
                <ul>
                    <?php
                    foreach ($this->macros('content', 'menu', [null, 1, 13], ['icon'])['items'] as $item): ?>
                        <li>
                            <div class="border">
                                <a href="<?= $item['link'] ?>">
                                    <div class="servicesBlock__icon">
                                        <img src="<?= $item['extended']['properties'][0]->getValue()->getFilePath(
                                            true
                                        ) ?>"
                                             alt="<?= $item['extended']['properties'][0]->getValue()->getAlt() ?>"
                                             title="<?= $item['extended']['properties'][0]->getValue()->getTitle() ?>">
                                    </div>

                                    <p><?= $item['name'] ?></p>
                                </a>
                            </div>
                        </li>
                    <?php
                    endforeach; ?>
                </ul>
            </div>
        </div>
    </section>

<?php
if ((int)$variables['pageId'] !== 13): ?>
    <?= $this->render($variables, 'news/children') ?>
<?php
endif;
